spring.application.name=pmanager

spring.datasource.url=jdbc:h2:mem:testedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar o console do H2 (opcional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Mostrar o SQL no console
spring.jpa.show-sql=true

# Criar ou atualizar o banco de dados automaticamente
spring.jpa.hibernate.ddl-auto=update